all:
	gcc hostinfo.c -o hostinfo
	gcc mydate.c -o mydate
	gcc printdir.c -o printdir
	gcc mycat.c -o mycat
	gcc pipe_ls.c -o pipe_ls
clean:
	rm -f hostinfo
	rm -f mydate
	rm -f printdir
	rm -f mycat
	rm -f pipe_ls
