all:
	gcc error_functions.c get_num.c svmsg_file_server.c -o svmsg_file_server
	gcc error_functions.c get_num.c svmsg_file_client.c -o svmsg_file_client
clean:
	clean -rf svmsg_file_server svmsg_file_client
