all:
	gcc alt_functions.c error_functions.c get_num.c server.c -o server
	gcc alt_functions.c error_functions.c get_num.c client.c -o client
	gcc alt_functions.c error_functions.c get_num.c clientDos.c -o clientDos
