myshell : shell.o parse.o builtin.o run_command.o is_background.o redirect_in.o redirect_out.o pipe_present.o pipe_command.o
	gcc shell.o parse.o builtin.o run_command.o is_background.o redirect_in.o redirect_out.o pipe_present.o pipe_command.o -o myshell
clean:
	rm -f shell.o
	rm -f parse.o
	rm -f builtin.o
	rm -f run_command.o
	rm -f is_background.o
	rm -f redirect_in.o
	rm -f redirect_out.o
	rm -f pipe_present.o 
	rm -f pipe_command.o
